In [1]:
strsample = 'Welcome to Python Learning'

In [2]:
strsample

'Welcome to Python Learning'

In [4]:
list_id=[1,2,3,4]
list_name = ["Rahul","Akash","Vikas","Shyam"]
lis = [list_id,list_name]

In [5]:
lis

[[1, 2, 3, 4], ['Rahul', 'Akash', 'Vikas', 'Shyam']]

In [6]:
my_list=[1,2,3,4,5,6]

In [7]:
import numpy as np

In [9]:
array = np.array(my_list,dtype=int)

In [10]:
array

array([1, 2, 3, 4, 5, 6])

In [14]:
print(type(array))
print(array.ndim)
print(len(array))
print(array.shape)

<class 'numpy.ndarray'>
1
6
(6,)


In [16]:
array2 =array.reshape(3,2)

In [19]:
print(array2)
print(array2.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [26]:
l1=[1,2,3,4,5]
l2=[1,2,4,5,6]
l3=[4,5,67,89,6]
array4 = np.array([l1,l2,l3],dtype=int)
print(array4)
print(type(array4))

[[ 1  2  3  4  5]
 [ 1  2  4  5  6]
 [ 4  5 67 89  6]]
<class 'numpy.ndarray'>


In [27]:
array4.T

array([[ 1,  1,  4],
       [ 2,  2,  5],
       [ 3,  4, 67],
       [ 4,  5, 89],
       [ 5,  6,  6]])

In [29]:
array4.max()
array4.min()

1

In [36]:

typ = ("Resistor","Inuductor","Capacitor")
cst_price = (345,560,700)
Selling_price=(500,690,750)
circuit_no = (typ,cst_price,Selling_price)
print(type(typ))

<class 'tuple'>


In [44]:
typ = ["Resistor","Inuductor","Capacitor"]
cst_price = [345,560,700]
Selling_price=[500,690,750]
circuit_no = [typ,cst_price,Selling_price]
print(type(typ))


<class 'list'>


In [50]:
dict1 = {"Resistor":(345,500),"Inductor":(560,690),"Capacitor":(700,750)}
print(dict1)
type(dict1)

{'Resistor': (345, 500), 'Inductor': (560, 690), 'Capacitor': (700, 750)}


dict

In [56]:
lis=[dict1]

In [57]:
lis

[{'Resistor': (345, 500), 'Inductor': (560, 690), 'Capacitor': (700, 750)}]

In [203]:
type(lis)
lis[0]

{'Resistor': (345, 500), 'Inductor': (560, 690), 'Capacitor': (700, 750)}

In [70]:
# A sigmoidal function is given by 𝑠𝑖𝑔𝑚𝑜𝑖𝑑=𝜎(𝑧)= 11+𝑒−𝑧 Define a sigmoidal function in Python. 
# Now take 𝑧=1,𝑧=−1,𝑧=0 and calculate values of sigmoid function (𝜎(𝑧)) defined by you.

import math

def sigmoid(z):
    return (11+ math.exp(-z))

In [76]:

print("If z=1 Sigmoid : ",sigmoid(1))
print("If z=1 Sigmoid : ",sigmoid(-1))
print("If z=1 Sigmoid : ",sigmoid(0))

If z=1 Sigmoid :  11.367879441171443
If z=1 Sigmoid :  13.718281828459045
If z=1 Sigmoid :  12.0


In [180]:
v=[100.0,150.0,10.0,35.0,50.0,64.0,35.0,54.0,60.0,70.0]
r=[200.0,500.0,250.0,300.0,350.0,450.0,240.0,450.0,350.0,200.0]
cur=0 
Total_current= 0
# Finding current flowing through Parellel circuit by i=v0/r0+...+v9/r9
for i in range(0,10):
    cur = v[i]/r[i]
    Total_current += cur 
print('Total current I through parellel circuit : ',round(Total_current,2))

# For finding voltageacross 1000 Ohm using V=IR(I=2.03,R=1000Ohm)
print('Voltage flowing throgh 1000Ohm : ',round((Total_current*1000),2))
 
    

Total current I through parellel circuit :  2.03
Voltage flowing throgh 1000Ohm :  2029.01


In [193]:
import numpy as np

v=[100.0,150.0,10.0,35.0,50.0,64.0,35.0,54.0,60.0,70.0]
r=[200.0,500.0,250.0,300.0,350.0,450.0,240.0,450.0,350.0,200.0]

array1 = np.array(v)
array2 = np.array(r)

print(array1)
print(type(array1))

print(array2)
print(type(array2))

array3 = array1/array2
# Finding current flowing through Parellel circuit by i=v1/r1+...+v10/r10
print('Finding Current flowing through each resisitor :',array3)
I=0
for i in array3:
    I +=i
    
print('Total Current Flowing throgh circuit',round(I,2))
# For finding voltageacross 1000 Ohm using V=IR(I=2.03,R=1000Ohm)
print('Voltage flowing throgh 1000Ohm : ',round((I*1000),2))
     
    

[100. 150.  10.  35.  50.  64.  35.  54.  60.  70.]
<class 'numpy.ndarray'>
[200. 500. 250. 300. 350. 450. 240. 450. 350. 200.]
<class 'numpy.ndarray'>
Finding Current flowing through each resisitor : [0.5        0.3        0.04       0.11666667 0.14285714 0.14222222
 0.14583333 0.12       0.17142857 0.35      ]
Total Current Flowing throgh circuit 2.03
Voltage flowing throgh 1000Ohm :  2029.01


In [197]:
import numpy as np

r=[200.0,500.0,250.0,300.0,350.0,450.0,240.0,450.0,350.0,200.0]

array4 = np.array(r)
# v=100v is constantfor the all resisitance.

array5 = 100/array4
I2=0
for i in array5:
    print(i)
    I2 += i
    
print('Total Current Flowing throgh circuit',round(I2,2))
# For finding voltageacross 1000 Ohm using V=IR(I=5.39,R=1000Ohm)
print('Voltage flowing throgh 1000Ohm : ',round((I2*1000),2))
    

0.5
0.2
0.4
0.3333333333333333
0.2857142857142857
0.2222222222222222
0.4166666666666667
0.2222222222222222
0.2857142857142857
0.5
Total Current Flowing throgh circuit 3.37
Voltage flowing throgh 1000Ohm :  3365.87


In [199]:
import numpy as np

v=[100.0,150.0,10.0,35.0,50.0,64.0,35.0,54.0,60.0,70.0]

array6 = np.array(v)

# r=250 ohm is constant for all the voltages

array7 = array6/250
I3=0
for i in array7:
    print(i)
    I3 += i
    
print('Total Current Flowing throgh circuit',round(I3,2))
# For finding voltageacross 1000 Ohm using V=IR(I=7.91,R=1000Ohm)
print('Voltage flowing throgh 1000Ohm : ',round((I3*1000),2))


0.4
0.6
0.04
0.14
0.2
0.256
0.14
0.216
0.24
0.28
Total Current Flowing throgh circuit 2.51
Voltage flowing throgh 1000Ohm :  2512.0
