In [1]:
import numpy as np

In [2]:
# Q-1. Create two numpy arrays. The first array, called arr1 should be of one dimension and consist of six elements of float type. The second array, called arr2 should be of two dimensions and each sub-array should consist of 5 elements of string type. Display these two numpy arrays.

arr1 = np.array([[1.0,2.0,3.0,4.0,5.0,6.0]])
print(arr1)
print(arr1.dtype)

[[1. 2. 3. 4. 5. 6.]]
float64


In [3]:
arr2 = np.array([['a','b','c','d','e'],['f','g','h','i','j'],['k','l','m','n','o']])
print(arr2)
print(arr2.dtype)

[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']
 ['k' 'l' 'm' 'n' 'o']]
<U1


In [4]:
# Q-2. For the arrays arr1 and arr2 created in Q.No.1, display the following properties: data type and dimensions. Reshape arr1 into a two dimensional array of 2 rows and three columns, and display the reshaped array. Similarly, reshape arr2 into a single dimensional array and display the reshaped array.

print(arr1.dtype)
print(arr1.shape)
print(arr2.dtype)
print(arr2.shape)

float64
(1, 6)
<U1
(3, 5)


In [5]:
arr_td = arr1.reshape(2,3)
print(arr_td)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
arr_sd = arr2.reshape(1,15)
print(arr_sd)

[['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o']]


In [7]:
# Q-3. Create a two dimensional array called arr3, of 3 rows and 4 columns which is initialized to zeroes. Create another single dimensional array called arr4, with 6 elements and which is initialized to ones. The type of arr4 is int.

arr3 = np.zeros([3,4],dtype=float)
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
arr4 = np.ones([1,6],dtype=int)
print(arr4)

[[1 1 1 1 1 1]]


In [9]:
# Q-4. Create a list called list1 with the elements 10,20,30,40,50. Now, create a numpy array called arr5 from list1, using the method asarray. The data type of arr5 is float. Similarly, create another array called arr6, from list1, using the method fromiter, whose data type is int. Display arr5 and arr6.
 
lis = [10,20,30,40,50]
print(lis)
arr5 = np.asarray(lis,dtype=float)
print('Array using list function')
print(arr5)

[10, 20, 30, 40, 50]
Array using list function
[10. 20. 30. 40. 50.]


In [10]:
for i in lis:
    print(i)
arr6 = np.fromiter(lis,dtype=int)
print('Array using iter function')
print(arr6)

10
20
30
40
50
Array using iter function
[10 20 30 40 50]


In [11]:
# Q-5. Create a numpy array called arr7 using the method arange. The starting value of this array is 12 and ending value is 99, with a step size of 3. Use the linspace method to create another array called arr8, where the starting value is 12 and ending value is 99 and which contains 50 evenly spaced elements.

arr7 = np.arange(12,99,3,dtype=int)
print(arr7)


[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96]


In [12]:
arr8 = np.linspace(12,99,50)
print(arr8)

[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


In [13]:
# Q-6. In the array arr2 defined in Q.No. 1, what is the output of the following statements: print(arr2), print(arr2[0:1]), print(arr2[1][3]), print (arr2[1])

print(arr2)
print('\n')
print(arr2[0:1])
print('\n')
print(arr2[1][3])
print('\n')
print (arr2[1])



[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']
 ['k' 'l' 'm' 'n' 'o']]


[['a' 'b' 'c' 'd' 'e']]


i


['f' 'g' 'h' 'i' 'j']


In [17]:
# Q-7. Create a two dimensional array called arr9 with the following elements: [101, 322, 768], [233, 124, 390], [534, 122, 216]. From arr9, create an array called arr10 which contains the elements 101, 322, 390, 122 using advanced integer indexing. Create another array called arr11 which contains elements of first and second rows, and second and third columns using slicing operations.

arr9 = np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print(arr9)
arr10 = arr9[[0,0,1,2],[0,1,2,1]]
print('\n',arr10)

[[101 322 768]
 [233 124 390]
 [534 122 216]]

 [101 322 390 122]


In [18]:
arr11 =arr9[0:2,(1,2)]
print(arr11)

[[322 768]
 [124 390]]


In [19]:
# Q-8. From array arr9 created in Q.No. 7, find all elements greater than 200 using boolean indexing, find all non-NaN elements, and find all non-float elements. Find the result of adding arrays arr9 and another array of 3 elements, using the concept of broadcasting.

print(arr9)
print('\n value greater than 200: ',arr9[arr9>200])

[[101 322 768]
 [233 124 390]
 [534 122 216]]

 value greater than 200:  [322 768 233 390 534 216]


In [20]:
print('All NaN element : ',arr9[~np.isnan(arr9)])

All NaN element :  [101 322 768 233 124 390 534 122 216]


In [21]:
print('All float type value',arr9[arr9.dtype != 'float'])

All float type value [[[101 322 768]
  [233 124 390]
  [534 122 216]]]


In [22]:
print(arr9)
print('\n')
arr12 = np.array([[10,20,30]])
print(arr12)
print('\n')
print('Addition of array : \n',arr9+arr12)

[[101 322 768]
 [233 124 390]
 [534 122 216]]


[[10 20 30]]


Addition of array : 
 [[111 342 798]
 [243 144 420]
 [544 142 246]]


In [23]:
# Q-9. For the array arr9, find its transpose. Find the result of joining the arrays arr1 and arr4 along axis 0.

print('Transpose of array :\n',arr9.T)

Transpose of array :
 [[101 233 534]
 [322 124 122]
 [768 390 216]]


In [24]:
print('Joining the two arrays arr 1 & arr 4 along with axis 0')
print (np.concatenate((arr1,arr4),axis=0))

Joining the two arrays arr 1 & arr 4 along with axis 0
[[1. 2. 3. 4. 5. 6.]
 [1. 1. 1. 1. 1. 1.]]


In [25]:
# Q-10. Using any two 2-dimensional arrays, demonstrate the working of the methods, hstack, vstack, hsplit and vsplit.

arr13 = np.array([[1,2],[3,4]])
print(arr13)

[[1 2]
 [3 4]]


In [26]:
arr13_hstack = np.hstack((arr13,arr13))
print(arr13_hstack)
arr13_vstack = np.vstack((arr13,arr13))
print(arr13_vstack)

[[1 2 1 2]
 [3 4 3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [27]:
arr13_hsplit = np.hsplit(arr13,2)
print(arr13_hsplit)
arr13_vsplit = np.vsplit(arr13,2)
print(arr13_vsplit)

[array([[1],
       [3]]), array([[2],
       [4]])]
[array([[1, 2]]), array([[3, 4]])]
